id: omega_footer
weight: -3
status: true
uuid: 2f38872c-f14c-48bf-b952-82b378ffb100
langcode: en
theme: omega
region: footer
plugin: 'system_menu_block:footer'
settings:
  module: system
  admin_label: ''
  label: Footer
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
