id: omega_powered
weight: -2
status: true
uuid: 77f915bc-191d-4c8f-b100-e3633575c063
langcode: en
theme: omega
region: footer
plugin: system_powered_by_block
settings:
  module: system
  admin_label: ''
  label: 'Powered by Drupal'
  label_display: '0'
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
