id: omega_login
weight: -2
status: true
uuid: 5b19bcaf-b25d-4b6b-9500-cbbbd7d2b0e2
langcode: en
theme: omega
region: sidebar_first
plugin: user_login_block
settings:
  module: user
  admin_label: ''
  label: 'User login'
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
