id: theme.omega.mobile_landscape
name: mobile_landscape
label: mobile_landscape
mediaQuery: 'all and (min-width: 480px) and (max-width: 767px)'
source: omega
sourceType: theme
weight: 2
multipliers:
  1x: 1x
status: true
langcode: en
