id: theme.omega.mobile_portrait
name: mobile_portrait
label: mobile_portrait
mediaQuery: 'all and (min-width: 320px) and (max-width: 479px)'
source: omega
sourceType: theme
weight: 1
multipliers:
  1x: 1x
status: true
langcode: en
